# Generated by Django 3.0.8 on 2021-08-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Mobile',
            field=models.CharField(max_length=10),
        ),
    ]
